### ISSUE TITLE
Unable to control volume with hardware buttons

### ISSUE THREAD

**Issue by pankookis** [phillyfan1138/onkyo-yatse-plugin#11]
The plug-in works flawless except it can't control the volume with the hardware buttons when Yatse is in focus, making the volume slider appear. 

If Yatse is not I focus, I can use the hardware buttons and it would be handy if it responded to them when Yatse is in focus. 

Am using the latest beta version of Yatse.

**Comment by danielhstahl** [comment]
Thanks for the heads up!  Just to clarify: when you say hardware buttons, do you mean the phone's volume buttons or the remote's hardware buttons? If you mean the phone's volume buttons, do you want the phone's hardware buttons to control the receiver's volume?    

I'm pretty busy at the moment so it may be a few days before I can look at this.

**Comment by pankookis** [comment]
Yes, I men the phone's volume buttons. If I exit Yatse, the volume buttons still control Yatse's volume and via the plug-in I can control my Onkyo receiver. 

But if Yatse is in focus, the volume buttons trigger the volume slider but the volume doesn't change. Can use the mute button on the slider but not increase/decrease the volume. 

With the upnp-plugin that's available on Google Play, I can control my receiver with the volume slider but that plug-in has several other problems making your plug-in far more superior. 

When I mention the volume slider, I mean the slider that's "integrated" in Yatse, not the general volume slider in Android. 

No worries about the time. I'm just glad I can control the volume with the same app I use for Kodi. :)

**Comment by danielhstahl** [comment]
I just tested this...my hardware volume buttons don't adjust anything on the receiver.  When Yatse is not in focus the hardware volume buttons do change the receiver volume for you?

**Comment by pankookis** [comment]
Yes. Then Yatse has a volume slider in android, just like "ringtone, media, system and notifications" (at least on my Galaxy S7). 

https://ibb.co/giSPvG image. I get a Yatse slider when playing media and Yatse is accessible through the notification. So when Yatse is out of focus this shows, and each press on my hardware volume button increase/decrease the volume by 1. 

https://ibb.co/iWb69b This on the other hand doesn't change anything, meaning the hardware buttons can't be used in Yatse. It's much more convenient to use the hardware buttons rather than being the "remote view" to focus and use software buttons (at least for me). This works in the upnp-plugin, and the hardware buttons increase/decrease the volume by 3 when Yatse is in focus.

**Comment by pankookis** [comment]
Edit to my comment. In the first picture... I'm not at home so there are no Yatse slider in the picture but it shows just like the ones in the picture when playing media.

**Comment by danielhstahl** [comment]
I can't get the volume to show up whether yatse is in focus or not.  @Tolriq , any ideas?

**Comment by Tolriq** [comment]
Activate lock screen controls option to have volume controls outside Yatse and have Android 5+

**Comment by danielhstahl** [comment]
I can't replicate this on my (new, not stock) Android phone.  Is the implementation of the hardware buttons supposed to be "out of the box" with the AVReceiverPluginService?

**Comment by Tolriq** [comment]
Well since I don't really know what you want to do it's quite hard to tell.

All volume functions are plugged into the plugin system whatever way they are used.

Hardware volume buttons with the lockscreen option work when something is playing in case you missed that detail :)

**Comment by danielhstahl** [comment]
So it sounds like in general the hardware volume control won't work unless on the lock screen.  @pankookis , I'm pretty busy with other things at the moment and since this seems like an optional feature I'll put it on the backburner for now.  I'll keep this issue open to remind me about this if I have time.

**Comment by pankookis** [comment]
Excellent! Thank you. :)

**Comment by danielhstahl** [comment]
I've actually had some time this morning and have been exploring how to implement this.   @Tolriq should I use ContentObserver as described in https://stackoverflow.com/questions/17192253/how-to-register-contentobserver-for-media-volume-change?  Or is there a better option?

**Comment by Tolriq** [comment]
You have nothing to do all is done at Yatse I have no idea what this issue and discussion is about but you have nothing to do more than handling the plugin API.

Should ask the users logs and more details :)

**Comment by danielhstahl** [comment]
Ok I was just able to replicate this.  I think this is actually a bug, but not sure if its in Yatse or in this plugin.  When I am in the settings menu (with both "lock screens control" and "show notifications" enabled) and I click the hardware volume buttons it changes the receiver volume and displays an Android volume control at the top.  However, when I'm in the "remote" section of the app and click the hardware buttons the Yatse volume control shows up in the middle and the receiver volume does not change.  @Tolriq I have a debug log; do you just want me to email it to Yatse support?

**Comment by danielhstahl** [comment]
I uploaded the debug log as part of https://yatse.tv/redmine/issues/1187.

**Comment by danielhstahl** [comment]
Ok, I got it to work doing the following:

- In General Settings, select both "Lock Screen Controls" and "Show notification"
- In Advanced Settings, select "Advanced", and have both "No volume keys" and "Volume keys show dialog" unselected

For some reason, this only worked after I selected "No volume keys", then unselected "Volume keys show dialog", and the unselected "No volume keys".  @pankookis , does this combination work for you?

**Comment by pankookis** [comment]
It works for me. Awesome that you managed to find that!

Thank you so much for your time! :)

**Comment by Tolriq** [comment]
If disabling show volume dialog solve a problem it means that the plugin does not correctly support the setVolume function but only volume plus / minus.

Manually changing the OS volume slide out of Yatse would produce the same problem.

**Comment by danielhstahl** [comment]
Well the plugin overrides setVolumeLevel.  Anyway, I'm closing this as it seems like it has been fixed.

**Comment by Tolriq** [comment]
Well it may overrides it but if the volume dialog does not work it means the plugin does not work :)

Not my plugin, not my bizness and no way to test, but well not having a quick way to set volume and needing to click tons of + / - to control is quite limiting.

**Comment by danielhstahl** [comment]
I looked back at some of my original research into the plugin...I don't think the Onkyo api allows for directly setting volume.  But I'll look into it some more.  If the API doesn't allow I'll make it clear that this is a limitation.

**Comment by pankookis** [comment]
@phillyfan1138 I don't know anything about anything when it comes to this but the upnp-plugin supported this with the same Onkyo. That plugin had really bad latency issues etc which yours don't suffer from but the "volume slider" worked in that. I don't know if that's what you're discussing but just so you know that the Onkyo receiver seem to support this.

**Comment by danielhstahl** [comment]
@pankookis @Tolriq I've just pushed a commit to master which fixes the issue.  It was a bug in the plugin; essentially the receiver was looking for a hexadecimal number without the "0x" beginning.

**Comment by Tolriq** [comment]
Not at home for 10 more days. You may want to build an APK before for test is user wants.

**Comment by Tolriq** [comment]
@phillyfan1138 finally not at home for a few more days. Can you please already add a commit to bump version code and version name so I can just compile and push to store when back home?

**Comment by danielhstahl** [comment]
I won't be at home till the 1st so I'll do it then.

**Comment by danielhstahl** [comment]
Just updated master branch with bumped code and version name.
