### ISSUE TITLE
Yatse Onkyo Plugin: Input and Woolfer Name and Parameters ?

### ISSUE THREAD

**Issue by freeload101** [phillyfan1138/onkyo-yatse-plugin#13]
* got the pro version
* figured I could use some kind of XML/API for the receiver ...and just add custom command in Kodi * I may end up just doing that if this silly thing wont work ...)
* realized its some stupid binary protocol
* installed the Onkyo plugin
* fumbled to find that I just attach the IP of the receiver to the current host ( not a new host ) this it not apparent in the API only in wiki
* added Onkyo and verified volume works
* clicked commands URL on the google play store for Yatse Onkyo Plugin and got 503's and 404's same for the link in the APK ;(
* wanting to add a few buttons:
* set input device 0-4
* set woofer level to +12
* set woofer level to -12
* noticed https://github.com/Tolriq/yatse-avreceiverplugin-api/ and https://github.com/miracle2k
* realized support page here
* search for support for Onkyo and did not find much
* posted this hoping he could pay or donate more for the custom param help :)

-RmcCurdyDOTcom

reference: https://yatse.tv/redmine/issues/1306#change-4796

**Comment by danielhstahl** [comment]
I'll be pretty busy for the next couple weeks so may be a little while before I can devote time to fixing this. 

What exactly is this issue that you are having?  Are the custom parameters not working?  What customer parameters have you tried?  The following repo (which you've linked to) has a lot of commands which should work here as well:  [miracle2k](https://github.com/miracle2k/onkyo-eiscp/tree/master/commands/main).

**Comment by freeload101** [comment]
Well that's the problem I don't know what to put as and example in these boxes at all. The get codes here url does not work but I assume just should be pointed from http://michael.elsdoerfer.name/onkyo/ to https://github.com/miracle2k/onkyo-eiscp. I tried  few guesses based on looking at the code

So for woofer I see https://github.com/miracle2k/onkyo-eiscp/blob/master/commands/main/SWL.yaml but what do I put in the box I tried various labels names and values

![image](https://user-images.githubusercontent.com/4307863/39711525-f0e352aa-51ed-11e8-9df9-97000ecff784.png)

**Comment by danielhstahl** [comment]
So in that case the parameter value should be "SWL+[HexNumber]", depending on the model.  For example, to increase the level by 12 decibels, the command should be "SWL+0C".  I'm using the Excel sheet linked to in the following issue: https://github.com/miracle2k/onkyo-eiscp/issues/35.  The number is in Hexadecimal and may not work depending on your Onkyo's version.

**Comment by freeload101** [comment]
Great that helps a lot!
