### ISSUE TITLE
Onkyo tx rz 710

### ISSUE THREAD

**Issue by deledav** [phillyfan1138/onkyo-yatse-plugin#15]
Hello,
Does your plugin allow you to turn on and off an onkyo tx rz710?
And can he control the volume?
David

**Comment by danielhstahl** [comment]
The rz710 is not on the list of AV receivers that the plugin is supposed to work with, but it doesn't hurt to try!  The plugin does allow to control volume.

**Comment by deledav** [comment]
ok i will try.

**Comment by deledav** [comment]
I have just seen that. The rz710 is there.
https://github.com/miracle2k/onkyo-eiscp/blob/master/eiscp-commands.yaml

**Comment by danielhstahl** [comment]
Cool it should work then
