### ISSUE TITLE
Crashing on null plugin restore

### ISSUE THREAD

**Issue by freeload101** [phillyfan1138/onkyo-yatse-plugin#16]
Here's my real-time trouble shooting guide / issues on restoring with Yatse Onkyo plugin.the issue seems to be the data that gets restored crashes the plugin because it's missing things like the IP address or something for the recever so the backup does not restore...

* got it working
* updated
* backed it up
* wipped data/uninstall
* reinstall
* resotrebackup
* crashes I think because the IP and PORT are missing from the plugin on backup/restore.

https://drive.google.com/file/d/1hZgnnmmQ6IPuTdAs4FBWQqUfXfzvccHP/view?usp=drivesdk

**Comment by danielhstahl** [comment]
Thanks for the detailed report!  I'll look into it this weekend.

**Comment by danielhstahl** [comment]
Is this a problem with other plugins?  When looking through the code there is no interface for saving IP addresses or port.  There is just an interface for importing settings, not exporting.   @Tolriq, any ideas?

**Comment by Tolriq** [comment]
There is everything to save too.

It's done via getSettingsVersion() and getSettings(). If you update the value returned by getSettingsVersion() Yatse knows it must backup your settings as more recent that the backup it have.

**Comment by danielhstahl** [comment]
I updated the code to be cleaner and add clarity to setters vs getters.  However, I was already storing the IP and Port as preferences on clicking the "OK" button and they are being loaded when re-creating the connection from "restoreSettings".  However, I can't replicate what you are seeing because none of my restores are working :).  When I try to restore from the cloud I have errors saying I can't restore settings.  (Error during host import, error during plugin settings import).

**Comment by Tolriq** [comment]
You need to be sure that you update the settings version each time there's a change.

Please open an issue with logs so I can look your error.

**Comment by danielhstahl** [comment]
I do update the settings version on each change.  https://github.com/phillyfan1138/onkyo-yatse-plugin/blob/master/sample/src/main/java/com/danielhstahl/plugin/avreceiver/onkyo/helpers/PreferencesHelper.java

As for the logs...when I turn on logging and then turn it off after having the error, it doesn't ask me to email the logs.  

Regardless, I'm still able to "save" my settings and "reload" them.  On reload, it doesn't try to install or load the plugin.  It just leaves the plugin blank.

**Comment by Tolriq** [comment]
Yes saving settings of plugins does not apply the plugin. But as soon as you'll select the plugin in the list it will restore the settings to the correct values and should not crash.

**Comment by danielhstahl** [comment]
I saved my yatse settings and plugin settings to the cloud.  I then uninstalled the plugin and removed all data from yatse.  When I restarted yatse it asked if i wanted to l load from cloud save.  I did and imported the settings.  It didn't import my hosts so I re-imported the hosts. I then re-installed the plugin.  The plugin did not have my saved settings either, but it didn't crash.

**Comment by Tolriq** [comment]
I need logs :)

But yes if you do not use Quick Restore that restore all you need to manually restore hosts.

I have not tried to reproduce and lack time, but I know the Yamaha plugin I maintain and use does not crash and data is restored :(

**Comment by danielhstahl** [comment]
Ok, I was successfully able to reload settings when uninstalling and re-installing the plugin.  The IP and port reloaded without issues.  There were no crashes.  Its going to be tricky to debug when I can't replicate the issue :).

**Comment by freeload101** [comment]
Logs of crash
* wipe data of plugin and yatse
* install yatse and import settings via local
* before I do anything install the plugin
* restore settings
* click setup gear for onkyo and then it crashes ugh now I have to @$#% with it again to get it back along with my custom buttons.
I have log email me freeload101@g̶m̷a̷i̶l̷.com

password is password https://www.rmccurdy.com/scripts/yatse-settings.yas

**Comment by danielhstahl** [comment]
I just followed your pattern to the letter and it didn't crash for me. I'm not seeing anything in the logs from the plugin itself.  Maybe @Tolriq can better read the logs.

**Comment by Tolriq** [comment]
Found the issue from logcat.

You have added new settings getReceiverCommunication that store boolean in the preferences. But you have not adapted the code from getSettingsAsJSON and importSettingsFromJSON those only support Strings. So when the settings are restored there's a string in the preferences when your code expect an boolean and getBoolean from getReceiverCommunication crash.

**Comment by danielhstahl** [comment]
Excellent catch @Tolriq !  @freeload101 , I've uploaded a release APK.  Can you test it and make sure that it works for you?  It should contain the fix that @Tolriq referenced.  

https://github.com/phillyfan1138/onkyo-yatse-plugin/releases/download/1.0.5/onkyo-debug.apk

**Comment by Tolriq** [comment]
@phillyfan1138 not fully read but I think your patch will crash all users that have never used the restore and actually have boolean currently.

You should save it under a new name and migrate is previous settings is here.

**Comment by danielhstahl** [comment]
Ok...is this sufficient?

https://github.com/phillyfan1138/onkyo-yatse-plugin/compare/patchexisting

**Comment by Tolriq** [comment]
This will prevent the crash but won't migrate the settings from previous users. I suppose with a warning in the changelog it's enough. Is that settings used a lot?

**Comment by danielhstahl** [comment]
It shouldn't be.  It should only be toggled "off" if there is an issue with communication between the receiver and the app.  

@freeload101 I've updated the 1.0.5 release. Let me know if that fixes your issue.

**Comment by freeload101** [comment]
LIKE A BOSS!

https://drive.google.com/file/d/1hUNjuYXNgPMq5lqGU9dg0oWgLYNOdLxo/view?usp=drivesdk

**Comment by danielhstahl** [comment]
Cool!  @Tolriq, anything you need from me to get this published?

**Comment by Tolriq** [comment]
Just a confirmation that master branch have all the fixes and everything.

Then update the versionCode and name in build.gradle of the plugin so that I can compile with prod keys and push.

**Comment by danielhstahl** [comment]
Confirmed and updated the versionCode.

**Comment by Tolriq** [comment]
Sorry for being late, but it's now in prod :) You can close.

**Comment by danielhstahl** [comment]
Excellent thank you!
