### ISSUE TITLE
Chain commands?

### ISSUE THREAD

**Issue by adiadi2** [phillyfan1138/onkyo-yatse-plugin#18]
Hello, I just want to ask you if there's a way to chain multiple commands to button, like: Turn on + input selector + set volume level?
thx

**Comment by danielhstahl** [comment]
Currently this isn't possible, but let me look into it and see if I can add that functionality.

**Comment by danielhstahl** [comment]
After thinking about this, I think it would be complex to add this capability.  And not sure its natively supported with Yatse. Closing for now, but feel free to comment if you feel differently.
