### ISSUE TITLE
Get AMT QSTN to Tasker for variable?

### ISSUE THREAD

**Issue by Cris--** [phillyfan1138/onkyo-yatse-plugin#19]
Hi,

is it possible to get the actual power state of the Onkyo receiver via AMT QSTN in to Tasker with the Yatse plugin.
Then i can use it as variable to check if receiver is already on/off.

**Comment by danielhstahl** [comment]
Cris, I'll look into this and get back to you.

**Comment by danielhstahl** [comment]
On second thought, could you create a custom command for AMT QSTN and then use https://yatse.tv/wiki/yatse-tasker-plugin to trigger that command from Tasker?

**Comment by danielhstahl** [comment]
Closing due to lack of response
